import type {
  ApprovalRecord,
  ConfigAssumption,
  ScanRecord,
  SessionUser,
  SyncLog,
  TicketRecord,
  V2StatusSnapshot,
  WaybillSnapshot,
} from "@/lib/types";

export interface DemoUser extends SessionUser {
  password: string;
}

const now = new Date("2026-07-06T17:00:00+08:00");

export const demoUsers: DemoUser[] = [
  {
    id: "user-reporter-01",
    name: "张晓宁",
    email: "reporter@v3.demo",
    warehouseId: "wh-sh-01",
    roles: ["reporter"],
    isActive: true,
    password: "demo123456",
  },
  {
    id: "user-l1-01",
    name: "李瑞",
    email: "l1@v3.demo",
    warehouseId: "wh-sh-01",
    roles: ["level1_approver"],
    isActive: true,
    password: "demo123456",
  },
  {
    id: "user-l2-01",
    name: "王倩",
    email: "l2@v3.demo",
    warehouseId: "wh-sh-01",
    roles: ["level2_approver", "qc_supervisor"],
    isActive: true,
    password: "demo123456",
  },
  {
    id: "user-admin-01",
    name: "陈楠",
    email: "admin@v3.demo",
    warehouseId: "wh-sh-01",
    roles: ["admin", "reporter", "level1_approver", "level2_approver", "qc_supervisor"],
    isActive: true,
    password: "demo123456",
  },
];

export const waybillSnapshots: WaybillSnapshot[] = [
  {
    waybillNo: "WB20260706001",
    customerName: "上海星芒贸易",
    receiverName: "赵晴",
    receiverPhone: "13800000001",
    amount: 860,
    status: "待出库",
    warehouseId: "wh-sh-01",
    syncedAt: now.toISOString(),
  },
  {
    waybillNo: "WB20260706002",
    customerName: "苏州观海电子",
    receiverName: "刘岸",
    receiverPhone: "13800000002",
    amount: 1480,
    status: "运输中",
    warehouseId: "wh-sh-01",
    syncedAt: now.toISOString(),
  },
  {
    waybillNo: "WB20260706003",
    customerName: "杭州临川家居",
    receiverName: "郑蓉",
    receiverPhone: "13800000003",
    amount: 320,
    status: "待签收",
    warehouseId: "wh-sh-01",
    syncedAt: now.toISOString(),
  },
];

export const initialTickets: TicketRecord[] = [
  {
    id: "ticket-001",
    ticketNo: "EX-20260706-001",
    waybillNo: "WB20260706001",
    title: "外观破损待审批",
    category: "quality_control",
    subtype: "外观破损",
    status: "level2_reviewing",
    amount: 860,
    warehouseId: "wh-sh-01",
    reporterId: "user-reporter-01",
    reporterName: "张晓宁",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 8).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 20).toISOString(),
    summary: "扫描发现纸箱开裂，已触发品控暂扣并自动建单。",
    dataSource: "snapshot",
    snapshotSyncedAt: now.toISOString(),
    currentApproverLevel: 2,
    retryCount: 0,
    version: 3,
    executionStatus: "not_started",
    closedAt: null,
    assignedApproverId: "user-l2-01",
    assignedApproverName: "王倩",
    dueAt: new Date(now.getTime() + 1000 * 60 * 60 * 4).toISOString(),
    timeoutEscalationCount: 1,
  },
  {
    id: "ticket-002",
    ticketNo: "EX-20260706-002",
    waybillNo: "WB20260706002",
    title: "客户拒收待一级审批",
    category: "logistics",
    subtype: "客户拒收",
    status: "level1_reviewing",
    amount: 1480,
    warehouseId: "wh-sh-01",
    reporterId: "user-admin-01",
    reporterName: "陈楠",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 35).toISOString(),
    summary: "司机回传客户拒收，需确认是否重新发货并生成赔付记录。",
    dataSource: "v2-live",
    snapshotSyncedAt: now.toISOString(),
    currentApproverLevel: 1,
    retryCount: 1,
    version: 2,
    executionStatus: "not_started",
    closedAt: null,
    assignedApproverId: "user-l1-01",
    assignedApproverName: "李瑞",
    dueAt: new Date(now.getTime() + 1000 * 60 * 60 * 2).toISOString(),
    timeoutEscalationCount: 0,
  },
  {
    id: "ticket-003",
    ticketNo: "EX-20260706-003",
    waybillNo: "WB20260706003",
    title: "超时未签收执行中",
    category: "logistics",
    subtype: "超时未签收",
    status: "executing",
    amount: 320,
    warehouseId: "wh-sh-01",
    reporterId: "user-reporter-01",
    reporterName: "张晓宁",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 18).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 15).toISOString(),
    summary: "已审批通过，正在执行重新派送。",
    dataSource: "snapshot",
    snapshotSyncedAt: now.toISOString(),
    currentApproverLevel: null,
    retryCount: 0,
    version: 4,
    executionStatus: "completed",
    closedAt: null,
    assignedApproverId: null,
    assignedApproverName: null,
    dueAt: null,
    timeoutEscalationCount: 0,
  },
];

export const initialApprovals: ApprovalRecord[] = [
  {
    id: "approval-001",
    ticketId: "ticket-001",
    level: 1,
    action: "approve",
    actorId: "user-l1-01",
    actorName: "李瑞",
    comment: "确认属于仓内破损，升级二级审批。",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "approval-002",
    ticketId: "ticket-002",
    level: 1,
    action: "submit",
    actorId: "user-admin-01",
    actorName: "陈楠",
    comment: "客户拒收，申请重新派送。",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 4).toISOString(),
  },
];

export const initialScans: ScanRecord[] = [
  {
    id: "scan-001",
    waybillNo: "WB20260706001",
    skuCode: "SKU-GLASS-01",
    operatorName: "王鹏",
    warehouseId: "wh-sh-01",
    scannedAt: new Date(now.getTime() - 1000 * 60 * 60 * 8).toISOString(),
    result: "abnormal",
    abnormalReason: "外观破损",
    holdStatus: "held",
    ticketId: "ticket-001",
  },
  {
    id: "scan-002",
    waybillNo: "WB20260706003",
    skuCode: "SKU-CHAIR-08",
    operatorName: "赵敏",
    warehouseId: "wh-sh-01",
    scannedAt: new Date(now.getTime() - 1000 * 60 * 60 * 2).toISOString(),
    result: "passed",
    abnormalReason: null,
    holdStatus: "normal",
    ticketId: null,
  },
];

export const initialSyncLogs: SyncLog[] = [
  {
    id: "sync-001",
    requestId: "req-v2-001",
    endpoint: "/api/v1/waybills/WB20260706001",
    method: "GET",
    requestSummary: "按运单号拉取详情",
    statusCode: 200,
    success: true,
    durationMs: 382,
    errorMessage: null,
    createdAt: new Date(now.getTime() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: "sync-002",
    requestId: "req-v2-002",
    endpoint: "/api/v1/skus/SKU-GLASS-01/ownership",
    method: "GET",
    requestSummary: "校验 SKU 归属",
    statusCode: 200,
    success: true,
    durationMs: 266,
    errorMessage: null,
    createdAt: new Date(now.getTime() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: "sync-003",
    requestId: "req-v2-003",
    endpoint: "/api/v1/waybills/WB20260706999",
    method: "GET",
    requestSummary: "上报前真实性校验",
    statusCode: 404,
    success: false,
    durationMs: 194,
    errorMessage: "V2 返回 404：运单不存在",
    createdAt: new Date(now.getTime() - 1000 * 60 * 90).toISOString(),
  },
];

export const v2Status: V2StatusSnapshot = {
  overall: "healthy",
  lastSuccessfulSyncAt: new Date(now.getTime() - 1000 * 60 * 10).toISOString(),
  successRate24h: 98.7,
  fallbackMode: false,
  notes: [
    "当前为 mock + 契约优先模式，接入真实 V2 后会自动切换实时调用。",
    "所有跨系统请求都应带 request_id，并写入 sync_logs。",
    "读接口允许 1-2 次重试，写接口默认不重试，避免重复回写。",
  ],
};

export const configAssumptions: ConfigAssumption[] = [
  {
    key: "一级/二级审批阈值",
    value: "1000 元",
    rationale: "1000 元以下默认一级审批，以上升级二级；以配置表而不是代码 if 语句实现。",
  },
  {
    key: "审批超时",
    value: "一级 2 小时，二级 4 小时",
    rationale: "确保异常尽快流转，同时给二级审批预留更长判断时间。",
  },
  {
    key: "品控暂扣超时",
    value: "90 分钟",
    rationale: "货物占仓成本高于纯审批等待，因此与审批超时独立配置。",
  },
  {
    key: "重提次数上限",
    value: "2 次",
    rationale: "避免无限驳回重提导致工单长期悬挂。",
  },
  {
    key: "V2 同步策略",
    value: "关键动作实时校验 + 非关键展示使用快照",
    rationale: "兼顾真实性和系统韧性。",
  },
];
